---
 
- hosts: 192.168.56.101 
  remote_user: user 
  tasks:
          - name: créations des conteneurs 
            shell: /home/user/DockerScripts/scriptCreateContainer {{ nb }} {{ image }}
            vars:
                    nb: "{{ nb }}"
                    image: "{{ image }}"
...
