#!/bin/bash

containerID=$1
length=${#containerID}
# 12 en bas représente le nombre de caractères dans un ID conteneur docker
if [ $length -eq 12 ]
then 
	curl -X "DELETE" 192.168.56.102:8888/api/routes/$containerID

elif [ $length -gt 12 ]
then
	containerID=${containerID:2:-1}
	IFS=' ' read -r -a cddd <<< "$containerID"
	for id in "${cddd[@]}"
	do
		curl -X "DELETE" 192.168.56.102:8888/api/routes/$id
	done
fi

