#!/bin/bash

containerID=$1
length=${#containerID}
# 12 en bas représente le nombre de caractères dans un ID conteneur docker
if [ $length -eq 12 ]
then
        POST 192.168.56.102:8888/api/routes/$containerID <<- EOF
	{ "target": "http://192.168.56.101:8000" }
	EOF
elif [ $length -gt 12 ]
then
        containerID=${containerID:2:-1}
        IFS=' ' read -r -a array <<< "$containerID"
        for id in "${array[@]}"
        do
                POST 192.168.56.102:8888/api/routes/$id <<- EOF
		{ "target": "http://192.168.56.101:8000" }
		EOF
        done
fi
