#!/bin/bash

containerID=$1
containerToken=$2
length=${#containerID}
# 12 en bas représente le nombre de caractères dans un ID conteneur docker
if [ $length -eq 12 ]
then 
	curl -X "DELETE" 192.168.56.102:8888/api/routes/$containerID/$containerToken

elif [ $length -gt 12 ]
then
	containerID=${containerID:2:-1}
	containerToken=${containerToken:2:-1}
	IFS=' ' read -r -a containerIDs <<< "$containerID"
	IFS=' ' read -r -a containerTokens <<< "$containerToken"
	length=${#containerIDs[@]}
	i=0
	while [ $i -lt $length ]
	do
		curl -X "DELETE" 192.168.56.102:8888/api/routes/${containerIDs[i]}/${containerTokens[i]}
		(( i++ ))
	done
fi

